name: mobiletesting
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0


# ---- PACKAGES ---- #
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.4

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8


  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  provider: ^6.1.2
  firebase_database: ^11.3.4
  location: ^8.0.0
  google_maps_flutter: ^2.11.0


# ---- PACKAGES END ---- #



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets: 
    - assets/
    

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  image: assets/logos/img.png
  android: true
  ios: true
  web: false